Products = {
    ["normal"] = {
        { name = "tosti", price = 2, amount = 50, },
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "kurkakola", price = 2, amount = 50, },
        { name = "twerks_candy", price = 2, amount = 50, },
        { name = "snikkel_candy", price = 2, amount = 50, },
        { name = "sandwich", price = 2, amount = 50, },
        { name = "beer", price = 7, amount = 50, },
        { name = "whiskey", price = 10, amount = 50, },
        { name = "vodka", price = 12, amount = 50, },
        { name = "lighter", price = 2, amount = 50, },
        { name = "rolling_paper", price = 2, amount = 5000,  },
        { name = "redwoodcigs", price = 50, amount = 50, info = { uses = 20 }, },
    },
    ["bar"] = {
        { name = "water_bottle", price = 2, amount = 50, },
        { name = "beer", price = 7, amount = 50, },
        { name = "whiskey", price = 10, amount = 50, },
        { name = "vodka", price = 70000, amount = 50, },
    },
    ["hardware"] = {
        { name = "weapon_wrench", price = 250, amount = 250, },
		{ name = "weapon_hammer", price = 250, amount = 250, },
		{ name = "screwdriverset", price = 350, amount = 50, },
		{ name = "phone", price = 750, amount = 50, },
		{ name = "radio", price = 2500, amount = 50, },
		{ name = "ammonia", price = 20, amount = 15, },
		{ name = "rope", price = 20, amount = 15, },
    },
    ["weedshop"] = {
        { name = "weapon_poolcue", price = 100, amount = 10, },
        { name = "empty_weed_bag", price = 1, amount = 1500, },
        { name = "rolling_paper", price = 1, amount = 1500, },
        { name = "water", price = 1, amount = 1500, },
        { name = "blottingpaper", price = 2, amount = 1500, },
        { name = "shears", price = 250, amount = 5, },
        { name = "cagoule", price = 25, amount = 1500, },
    },
    ["gearshop"] = {
        { name = "diving_gear", price = 2500, amount = 10, },
        { name = "jerry_can", price = 200, amount = 50, },
        { name = "fishingrod", price = 100, amount = 1000, },
        { name = "fishingbait", price = 2, amount = 1000, },
        { name = "skateboard", price = 250, amount = 1000, },
        { name = "spray", price = 200, amount = 10, },
        { name = "spray_remover", price = 100, amount = 10, },
        { name = "backpack_small", price = 750, amount = 5, },
        { name = "backpack_medium", price = 1250, amount = 10, },
        { name = "backpack_large", price = 2000, amount = 5, },
        { name = "kq_outfitbag", price = 2000, amount = 5, },
    },
    ["leisureshop"] = {
        { name = "parachute", price = 2500, amount = 10, },
        { name = "binoculars", price = 50, amount = 50, },
        { name = "diving_gear", price = 2500, amount = 10, },
        { name = "diving_fill", price = 500, amount = 10, },
        { name = "syphoningkit", price = 2500, amount = 10, },
    },
    ["weapons"] = {
        { name = "weapon_bat", price = 250, amount = 250, },
        { name = "weapon_hatchet",price = 250, amount = 250, },
    },
    ["pills"] = {
        { name = "painkillers", price = 100, amount = 250, },
    },
    ["digitalden"] = {
        { name = "classic_phone", price = 850, amount = 10, },
        { name = "mp3", price = 250, amount = 10, },
        { name = "fitbit", price = 500, amount = 10, },
        { name = "radio", price = 2000, amount = 10, },
        { name = "black_phone", price = 850, amount = 10, },
        { name = "blue_phone", price = 850, amount = 10, },
        { name = "gold_phone", price = 850, amount = 10, },
        { name = "red_phone", price = 850, amount = 10, },
        { name = "green_phone", price = 850, amount = 10, },
        { name = "greenlight_phone", price = 850, amount = 10, },
        { name = "pink_phone", price = 850, amount = 10, },
        { name = "white_phone", price = 850, amount = 10, },
        { name = "sim_card", price = 99, amount = 10, },
        { name = "phone_module", price = 200, amount = 10, },
    },
    ["coffeeplace"] = {
        { name = "coffee", price = 5, amount = 500 },
        { name = "lighter", price = 2, amount = 50 },
    },
    ["electronics"] = {
        { name = "screwdriverset", price = 350, amount = 50, },
        { name = "binoculars", price = 50, amount = 50, },
    },
    ["vending"] = {
        { name = "water_bottle", price = 100, amount = 25, },
        { name = "kurkakola", price = 100, amount = 25, },
        { name = "sprunk", price = 100, amount = 25, },
        { name = "sprunklight", price = 100, amount = 25, },
        { name = "ecola", price = 100, amount = 25, },
        { name = "ecolalight", price = 100, amount = 25, },
        { name = "twerks_candy", price = 100, amount = 25, },
        { name = "snikkel_candy", price = 100, amount = 25, },
    },
    ["masker"] = {
        { name = "terror", price = 500, amount = 250, },
        { name = "hockeymask", price = 500, amount = 250, },
        { name = "blackbandana", price = 500, amount = 50, },
        { name = "tshirtmask", price = 500, amount = 50, },
        { name = "scarecrowmask", price = 500, amount = 50, },
        { name = "scarf", price = 500, amount = 50, },
        { name = "monkeymask", price = 500, amount = 50, },
        { name = "skullmask", price = 500, amount = 50, },
        { name = "terrorwit", price = 500, amount = 50, },
        { name = "feest", price = 500, amount = 50, },
        { name = "noselong", price = 500, amount = 150, },
        { name = "blauw", price = 500, amount = 150, },
        { name = "skullzwart", price = 500, amount = 250, },
        { name = "silver", price = 500, amount = 250, },
        { name = "zwart1", price = 500, amount = 50, },
        { name = "zwart2", price = 500, amount = 50, },
        { name = "please", price = 500, amount = 50, },
        { name = "sok", price = 500, amount = 50, },
        { name = "zak", price = 500, amount = 50, },
        { name = "groen", price = 500, amount = 50, },
        { name = "bandanab", price = 500, amount = 50, },
        { name = "bivak1", price = 500, amount = 50, },
        { name = "roodc", price = 500, amount = 150, },
        { name = "clown", price = 500, amount = 150, },
        { name = "gorilla", price = 500, amount = 50, },
        { name = "paard", price = 500, amount = 50, },
        { name = "paardu", price = 500, amount = 50, },
        { name = "skullr", price = 500, amount = 50, },
        { name = "masker3", price = 500, amount = 50, },
        { name = "helm1", price = 500, amount = 50, },
    },
}